### ISSUE TITLE
充值挖矿折合投票算法调整

### ISSUE THREAD

**Issue by wliyongfeng** [chainpool/chainx-electron#26]
1.  `price`含义变更
![wechatimg2871](https://user-images.githubusercontent.com/2264908/52936260-94702800-3396-11e9-9a5b-238063d07940.png)
2. 链上有一个存储是'充值挖矿折扣'，折合投票这里要乘上'充值挖矿折扣'

**Comment by yuelipeng** [comment]
充值挖矿折扣 给你们 自动计算在RPC的价格里了，前端不用单独再计算了。

**Comment by yuelipeng** [comment]
移动平均价(PCX)   改为  挖矿算力(PCX)

**Comment by yuelipeng** [comment]
SDOT提示：固定算力，永久挖矿
其余提示：每日均价 * 50%
