### ISSUE TITLE
金额输入控件要控制精度

### ISSUE THREAD

**Issue by yuelipeng** [chainpool/chainx-electron#28]
按照不同资产，控制不同精度，像交易数量控件一样。
![image](https://user-images.githubusercontent.com/2844215/52985485-05631e80-342f-11e9-9b8e-6860db3e70f7.png)

**Comment by yuelipeng** [comment]
包括所有金额相关的输入框

**Comment by shuxialanhu** [comment]
赎回数量必须大于0小于投票数量
